version: "3"

services:
    nginx:
        container_name: skilloupe-nginx
        build:
            context: ./docker-local/nginx/
        ports:
            - "8000:80"
        volumes:
            - ./src/:/usr/share/nginx/html
            - ./docker-local/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker-local/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php7
        networks:
            - common

    php7:
        container_name: skilloupe-php7
        build:
            context: ./docker-local/php7/
        ports:
            - "9000:9000"
        environment:
            APP_ENV: local
            DB_HOST: skilloupe-mysql
            DB_NAME: skilloupe
            DB_USER: root
            DB_PASS: password
        volumes:
            - ./src/:/usr/share/nginx/html
            - ./docker-local/php7/config/php.ini:/etc/php.ini
            - ./docker-local/php7/config/www.conf:/etc/php-fpm.d/www.conf
            - ./docker-local/php7/config/php-fpm.conf:/etc/php-fpm.conf
        networks:
            - common

    mysql:
        container_name: skilloupe-mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: skilloupe
        hostname: localhost
        networks:
            - common

    mysql-test:
        container_name: skilloupe-test-mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: skilloupe
        hostname: localhost
        networks:
            - common

volumes:
    skilloupe-dbdata:
        driver: local

networks:
    common:
        driver: bridge
