<?php

return [
    'DB' => [
        'SEX' => [
            'MALE'      => 1,
            'FEMALE'    => 2,
            'OTHER'     => 3,
        ],
    ],
    'PROJECT' => [
        'SYSTEM' => [
            'Web',
            'モバイルアプリケーション',
            'Windowsアプリケーション',
            'Macアプリケーション',
            'クライアント・サーバー',
            'スタンドアローン',
        ],
        'REGION' => [
            'フロントエンド',
            'バックエンド',
            'インフラ',
            'アーキテクチャ',
            '運用・保守',
        ],
        'ROLE' => ['PMO', 'PM', 'PL', 'SE', 'PG', 'テスター',],
        'DEV_METHOD' => [
            'ウォーターフォール',
            'アジャイル',
            'プロトタイプ',
            'スクラム',
        ],
        'PROCESS' => [
            '要件定義',
            '基本設定',
            '詳細設計',
            '実装',
            '単体テスト',
            '内部結合テスト',
            '外部結合テスト',
            'リリース',
            '運用・保守',
        ],
        'LANG_AND_FW' => [
            'PHP',
            'Ruby',
            'JavaScript',
            'Java',
            'Go',
            'Swift',
            'C',
            'C++',
            'C#',
            'CSS',
            'Laravel',
            'CakePHP',
            'Phalcon',
            'Rails',
            'jQuery',
            'Vue.js',
            'React',
            'Angular',
            'Spring',
            '.NET',
            'Bulma',
            'Buefy',
            'Vuetify',
            'Element UI',
            'Onsen UI',
            'Bootstrap',
        ],
        'OS_AND_MW' => [
            'Windows Server',
            'Ubuntu',
            'CentOS',
            'RedHat',
            'iOS',
            'Android',
            'Windows',
            'Mac',
            'Apache',
            'Nginx',
            'Tomcat',
            'MySQL',
            'PostgreSQL',
            'SQLite',
        ],
        'TOOL' => [
            'Visual Studio',
            'Visual Studio Code',
            'Eclipse',
            'PhpStorm',
            'Sublime Text',
            'Git',
            'GitHub',
            'GitLab',
            'Docker',
            'Vagrant',
            'Backlog',
            'Redmine',
            'JIRA',
        ],
    ],
    'SKILL' => [
        'SKILL' => [
            'PHP',
            'Ruby',
            'JavaScript',
            'Java',
            'Go',
            'Swift',
            'C',
            'C++',
            'C#',
            'CSS',
            'Apache',
            'Nginx',
            'Tomcat',
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'アプリケーション・アーキテクチャ',
            'インフラストラクチャ・アーキテクチャ',
            'インテグレーション・アーキテクチャ',
            'プロジェクトマネジメント',
            'テックリード',
            'Webディレクション',
        ],
        'TYPE' => [
            'プログラミング言語',
            'ミドルウェア',
            'アーキテクチャ',
            'マネジメント'
        ],
        'TOOL' => [
            'Laravel',
            'CakePHP',
            'Phalcon',
            'Rails',
            'jQuery',
            'Vue.js',
            'React',
            'Angular',
            'Spring',
            '.NET',
            'Bulma',
            'Buefy',
            'Vuetify',
            'Element UI',
            'Onsen UI',
            'Bootstrap',
            'Visual Studio',
            'Visual Studio Code',
            'Eclipse',
            'PhpStorm',
            'Sublime Text',
            'Git',
            'GitHub',
            'GitLab',
            'Docker',
            'Vagrant',
            'Backlog',
            'Redmine',
            'JIRA',
        ],
        'PLATFORM' => [
            'Windows Server',
            'Ubuntu',
            'CentOS',
            'RedHat',
            'iOS',
            'Android',
            'Windows',
            'Mac',
            'AWS',
            'GCP',
            'Azure',
            'Firebase',
        ],
        'SYSTEM' => [
            'Web',
            'モバイルアプリケーション',
            'Windowsアプリケーション',
            'Macアプリケーション',
            'クライアント・サーバー',
            'スタンドアローン',
        ],
        'LEVEL_NOTE' => [
            1 => '1PJ経験有、独学レベル',
            2 => '複数PJ経験有、詳細設計書、単体テスト仕様作成経験あり',
            3 => '複数PJ経験有、要件定義、基本設計が可能',
            4 => '開発チームリーダー、仕様書やソースコードのレビューワーレベル',
            5 => 'アーキテクト、技術統括レベル',
        ]
    ],
    'QUALIFICATION' => [
        'IPA ITパスポート',
        'IPA 情報セキュリティマネジメント',
        'IPA 基本情報技術者',
        'IPA 応用情報技術者',
        'IPA ITストラテジスト',
        'IPA システムアーキテクト',
        'IPA プロジェクトマネージャ',
        'IPA ネットワークスペシャリスト',
        'IPA データベーススペシャリスト',
        'IPA エンベデッドシステムスペシャリスト',
        'IPA ITサービスマネージャ',
        'IPA システム監査技術者',
        'Oracle Java SE 11 Silver',
        'Oracle Java SE 11 Gold',
        'Oracle Java SE 8 Silver',
        'Oracle Java SE 8 Gold',
        'Oracle Java SE 7 Silver',
        'Oracle Java SE 7 Gold',
        'Oracle Java EE 6 Web Services Developer',
        'Oracle Java EE 6 Web Component Developer',
        'Oracle Java EE 6 Enterprise JavaBeans Developer',
        'Ruby Association Certified Ruby Programmer Silver version 2.1',
        'Ruby Association Certified Ruby Programmer Gold version 2.1',
        'PHP7技術者認定初級',
        'PHP5技術者認定上級',
        'AWS クラウドプラクティショナー',
        'AWS ソリューションアーキテクト',
        'AWS ソリューションアーキテクト',
        'AWS デベロッパー',
        'AWS SysOpsアドミニストレータ',
        'AWS DevOpsエンジニア',
    ],
    'SEARCH_OPERATOR_LABEL' => [
        'NUMBER' => ['一致', '以上', '以下'],
        'DATETIME' => ['一致', '以降', '以前'],
    ],
    'SEARCH_OPERATOR' => [
        'NUMBER' => [
            '一致' => '=',
            '以上' => '>=',
            '以下' => '<=',
        ],
        'DATETIME' => [
            '一致' => '=',
            '以降' => '>=',
            '以前' => '<=',
        ],
    ],
];
